### PR TITLE
Add index annotations

### LINKED ISSUE #2: Add annotations for indices
```
User.db.indexes(:users)
{
    :unique_users_uid => {
        :columns => [
            [0] :uid
        ],
         :unique => true
    }
}
```

I can work on a PR for this..

### PR DESCRIPTION
**Pull request by ktaragorn**
Fixes #2

### CODE REVIEW

**Comment by ktaragorn** [comment]
Not ready.. needs to clear on each annotate

**Comment by kennym** [comment]
This looks good.. thank you for working on this! I'll merge once it's ready :)

**Comment by ktaragorn** [comment]
Hi @kennym , it is ready after my last commit, am using it already

**Comment by kennym** [comment]
Thank you @ktaragorn!

**Comment by ktaragorn** [comment]
Great tnx, is it published to rubygems?

**Pull request merged**
